shared:
  tg_bot_token: <%= ENV['TG_BOT_TOKEN'] %>
  tg_proxy: <%= ENV['TG_BOT_PROXY'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  loopback_url: <%= ENV['LOOPBACK_URL'] %>
  redis_current_url: <%= ENV['REDIS_CURRENT_URL'] %>
  redis_sidekiq_url: <%= ENV['REDIS_SIDEKIQ_URL'] %>
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>

test:
  tg_bot_token: tg_bot_token
  tg_proxy: http://example.com
